language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t oateakk/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true oateakk/docker-react npm run test
